GET http://localhost:3000/lectures

###

GET http://localhost:3000/lectures/5cf86dd0f8e9f94fa318c27a


###
POST http://localhost:3000/lectures
content-type: application/json

{
    "id" : 1,
    "lecture" : "mongodb part 1",
    "course" : "CS572"
}

###

PUT http://localhost:3000/lectures
content-type: application/json
{ 
    "id":  4 ,
    "lecture" : "asynchronous in js... ",
    "course" : "CS572"
}


DELETE http://localhost:3000/lectures
content-type: application/json

{
    "course" : "CS572"
}