GET http://localhost:3000/lectures

###

GET http://localhost:3000/lectures/5cf86eb2f8e9f94fa318c27c


###
POST http://localhost:3000/lectures
content-type: application/json

{
    "lecture" : "mongodb part 1",
    "course" : "CS572"
}

###

PUT http://localhost:3000/lectures
content-type: application/json

{
    "_id": "5cf872fe567eda5d66e10646",
    "lecture": "mongodb part 1 updated",
    "course": "CS572"
  }

###

DELETE http://localhost:3000/lectures
content-type: application/json

{
    "course" : "CS572"
}