GET http://localhost:3000/restaurant/getAll

###

GET http://localhost:3000/restaurant/getAllSpecificFields1

###

GET http://localhost:3000/restaurant/getAllSpecificFields2

####

GET http://localhost:3000/restaurant/getAllSpecificFields3

####

GET http://localhost:3000/restaurant/getAllSpecificFields4

###

GET http://localhost:3000/restaurant/getAllSpecificFields5


####

GET http://localhost:3000/restaurant/getAllSpecificFields6


###

GET http://localhost:3000/restaurant/getAllSpecificFields7

#####

GET http://localhost:3000/restaurant/getAllSpecificFields8